/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CompleteSetupRouteImport } from './routes/complete-setup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EverydayLifeRouteImport } from './routes/everyday-life'
import { Route as ExpatGuideRouteImport } from './routes/expat-guide'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as AdministrativeIndexRouteImport } from './routes/administrative.index'
import { Route as AdministrativeBankRouteImport } from './routes/administrative.bank'
import { Route as AdministrativeCmdRouteImport } from './routes/administrative.cmd'
import { Route as AdministrativeHealthRouteImport } from './routes/administrative.health'
import { Route as AdministrativeNifRouteImport } from './routes/administrative.nif'
import { Route as AdministrativeNissRouteImport } from './routes/administrative.niss'
import { Route as PropertyIndexRouteImport } from './routes/property.index'
import { Route as PropertyCleaningRouteImport } from './routes/property.cleaning'
import { Route as PropertyPurchaseRouteImport } from './routes/property.purchase'
import { Route as PropertyRentalRouteImport } from './routes/property.rental'
import { Route as RelocationIndexRouteImport } from './routes/relocation.index'
import { Route as RelocationVisasRouteImport } from './routes/relocation.visas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteSetupRoute = CompleteSetupRouteImport.update({
  id: '/complete-setup',
  path: '/complete-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EverydayLifeRoute = EverydayLifeRouteImport.update({
  id: '/everyday-life',
  path: '/everyday-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpatGuideRoute = ExpatGuideRouteImport.update({
  id: '/expat-guide',
  path: '/expat-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeIndexRoute = AdministrativeIndexRouteImport.update({
  id: '/administrative/',
  path: '/administrative/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeBankRoute = AdministrativeBankRouteImport.update({
  id: '/administrative/bank',
  path: '/administrative/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeCmdRoute = AdministrativeCmdRouteImport.update({
  id: '/administrative/cmd',
  path: '/administrative/cmd',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeHealthRoute = AdministrativeHealthRouteImport.update({
  id: '/administrative/health',
  path: '/administrative/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeNifRoute = AdministrativeNifRouteImport.update({
  id: '/administrative/nif',
  path: '/administrative/nif',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativeNissRoute = AdministrativeNissRouteImport.update({
  id: '/administrative/niss',
  path: '/administrative/niss',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIndexRoute = PropertyIndexRouteImport.update({
  id: '/property/',
  path: '/property/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCleaningRoute = PropertyCleaningRouteImport.update({
  id: '/property/cleaning',
  path: '/property/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPurchaseRoute = PropertyPurchaseRouteImport.update({
  id: '/property/purchase',
  path: '/property/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRentalRoute = PropertyRentalRouteImport.update({
  id: '/property/rental',
  path: '/property/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const RelocationIndexRoute = RelocationIndexRouteImport.update({
  id: '/relocation/',
  path: '/relocation/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelocationVisasRoute = RelocationVisasRouteImport.update({
  id: '/relocation/visas',
  path: '/relocation/visas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/everyday-life': typeof EverydayLifeRoute
  '/expat-guide': typeof ExpatGuideRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/transfers': typeof TransfersRoute
  '/administrative/bank': typeof AdministrativeBankRoute
  '/administrative/cmd': typeof AdministrativeCmdRoute
  '/administrative/health': typeof AdministrativeHealthRoute
  '/administrative/nif': typeof AdministrativeNifRoute
  '/administrative/niss': typeof AdministrativeNissRoute
  '/property/cleaning': typeof PropertyCleaningRoute
  '/property/purchase': typeof PropertyPurchaseRoute
  '/property/rental': typeof PropertyRentalRoute
  '/relocation/visas': typeof RelocationVisasRoute
  '/administrative/': typeof AdministrativeIndexRoute
  '/property/': typeof PropertyIndexRoute
  '/relocation/': typeof RelocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/everyday-life': typeof EverydayLifeRoute
  '/expat-guide': typeof ExpatGuideRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/transfers': typeof TransfersRoute
  '/administrative/bank': typeof AdministrativeBankRoute
  '/administrative/cmd': typeof AdministrativeCmdRoute
  '/administrative/health': typeof AdministrativeHealthRoute
  '/administrative/nif': typeof AdministrativeNifRoute
  '/administrative/niss': typeof AdministrativeNissRoute
  '/property/cleaning': typeof PropertyCleaningRoute
  '/property/purchase': typeof PropertyPurchaseRoute
  '/property/rental': typeof PropertyRentalRoute
  '/relocation/visas': typeof RelocationVisasRoute
  '/administrative': typeof AdministrativeIndexRoute
  '/property': typeof PropertyIndexRoute
  '/relocation': typeof RelocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/complete-setup': typeof CompleteSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/everyday-life': typeof EverydayLifeRoute
  '/expat-guide': typeof ExpatGuideRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/transfers': typeof TransfersRoute
  '/administrative/bank': typeof AdministrativeBankRoute
  '/administrative/cmd': typeof AdministrativeCmdRoute
  '/administrative/health': typeof AdministrativeHealthRoute
  '/administrative/nif': typeof AdministrativeNifRoute
  '/administrative/niss': typeof AdministrativeNissRoute
  '/property/cleaning': typeof PropertyCleaningRoute
  '/property/purchase': typeof PropertyPurchaseRoute
  '/property/rental': typeof PropertyRentalRoute
  '/relocation/visas': typeof RelocationVisasRoute
  '/administrative/': typeof AdministrativeIndexRoute
  '/property/': typeof PropertyIndexRoute
  '/relocation/': typeof RelocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/complete-setup'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/everyday-life'
    | '/expat-guide'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tours'
    | '/transfers'
    | '/administrative/bank'
    | '/administrative/cmd'
    | '/administrative/health'
    | '/administrative/nif'
    | '/administrative/niss'
    | '/property/cleaning'
    | '/property/purchase'
    | '/property/rental'
    | '/relocation/visas'
    | '/administrative/'
    | '/property/'
    | '/relocation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/complete-setup'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/everyday-life'
    | '/expat-guide'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tours'
    | '/transfers'
    | '/administrative/bank'
    | '/administrative/cmd'
    | '/administrative/health'
    | '/administrative/nif'
    | '/administrative/niss'
    | '/property/cleaning'
    | '/property/purchase'
    | '/property/rental'
    | '/relocation/visas'
    | '/administrative'
    | '/property'
    | '/relocation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/complete-setup'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/everyday-life'
    | '/expat-guide'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tours'
    | '/transfers'
    | '/administrative/bank'
    | '/administrative/cmd'
    | '/administrative/health'
    | '/administrative/nif'
    | '/administrative/niss'
    | '/property/cleaning'
    | '/property/purchase'
    | '/property/rental'
    | '/relocation/visas'
    | '/administrative/'
    | '/property/'
    | '/relocation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  CompleteSetupRoute: typeof CompleteSetupRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EverydayLifeRoute: typeof EverydayLifeRoute
  ExpatGuideRoute: typeof ExpatGuideRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ToursRoute: typeof ToursRoute
  TransfersRoute: typeof TransfersRoute
  AdministrativeBankRoute: typeof AdministrativeBankRoute
  AdministrativeCmdRoute: typeof AdministrativeCmdRoute
  AdministrativeHealthRoute: typeof AdministrativeHealthRoute
  AdministrativeNifRoute: typeof AdministrativeNifRoute
  AdministrativeNissRoute: typeof AdministrativeNissRoute
  PropertyCleaningRoute: typeof PropertyCleaningRoute
  PropertyPurchaseRoute: typeof PropertyPurchaseRoute
  PropertyRentalRoute: typeof PropertyRentalRoute
  RelocationVisasRoute: typeof RelocationVisasRoute
  AdministrativeIndexRoute: typeof AdministrativeIndexRoute
  PropertyIndexRoute: typeof PropertyIndexRoute
  RelocationIndexRoute: typeof RelocationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-setup': {
      id: '/complete-setup'
      path: '/complete-setup'
      fullPath: '/complete-setup'
      preLoaderRoute: typeof CompleteSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/everyday-life': {
      id: '/everyday-life'
      path: '/everyday-life'
      fullPath: '/everyday-life'
      preLoaderRoute: typeof EverydayLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expat-guide': {
      id: '/expat-guide'
      path: '/expat-guide'
      fullPath: '/expat-guide'
      preLoaderRoute: typeof ExpatGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/': {
      id: '/administrative/'
      path: '/administrative'
      fullPath: '/administrative/'
      preLoaderRoute: typeof AdministrativeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/bank': {
      id: '/administrative/bank'
      path: '/administrative/bank'
      fullPath: '/administrative/bank'
      preLoaderRoute: typeof AdministrativeBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/cmd': {
      id: '/administrative/cmd'
      path: '/administrative/cmd'
      fullPath: '/administrative/cmd'
      preLoaderRoute: typeof AdministrativeCmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/health': {
      id: '/administrative/health'
      path: '/administrative/health'
      fullPath: '/administrative/health'
      preLoaderRoute: typeof AdministrativeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/nif': {
      id: '/administrative/nif'
      path: '/administrative/nif'
      fullPath: '/administrative/nif'
      preLoaderRoute: typeof AdministrativeNifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrative/niss': {
      id: '/administrative/niss'
      path: '/administrative/niss'
      fullPath: '/administrative/niss'
      preLoaderRoute: typeof AdministrativeNissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/': {
      id: '/property/'
      path: '/property'
      fullPath: '/property/'
      preLoaderRoute: typeof PropertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/cleaning': {
      id: '/property/cleaning'
      path: '/property/cleaning'
      fullPath: '/property/cleaning'
      preLoaderRoute: typeof PropertyCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/purchase': {
      id: '/property/purchase'
      path: '/property/purchase'
      fullPath: '/property/purchase'
      preLoaderRoute: typeof PropertyPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/rental': {
      id: '/property/rental'
      path: '/property/rental'
      fullPath: '/property/rental'
      preLoaderRoute: typeof PropertyRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relocation/': {
      id: '/relocation/'
      path: '/relocation'
      fullPath: '/relocation/'
      preLoaderRoute: typeof RelocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relocation/visas': {
      id: '/relocation/visas'
      path: '/relocation/visas'
      fullPath: '/relocation/visas'
      preLoaderRoute: typeof RelocationVisasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  CompleteSetupRoute: CompleteSetupRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  EverydayLifeRoute: EverydayLifeRoute,
  ExpatGuideRoute: ExpatGuideRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ToursRoute: ToursRoute,
  TransfersRoute: TransfersRoute,
  AdministrativeBankRoute: AdministrativeBankRoute,
  AdministrativeCmdRoute: AdministrativeCmdRoute,
  AdministrativeHealthRoute: AdministrativeHealthRoute,
  AdministrativeNifRoute: AdministrativeNifRoute,
  AdministrativeNissRoute: AdministrativeNissRoute,
  PropertyCleaningRoute: PropertyCleaningRoute,
  PropertyPurchaseRoute: PropertyPurchaseRoute,
  PropertyRentalRoute: PropertyRentalRoute,
  RelocationVisasRoute: RelocationVisasRoute,
  AdministrativeIndexRoute: AdministrativeIndexRoute,
  PropertyIndexRoute: PropertyIndexRoute,
  RelocationIndexRoute: RelocationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
